### ISSUE TITLE
Issue with arrow R package but only when running inside ryp

### ISSUE THREAD

**Issue by fkgruber** [Wainberg/ryp#4] opened 2024-11-07 19:30 UTC
Hi
I'm trying to run ryp in an existing conda environment.
If I run R directly I can load arrow. However if I do it using ryp I get an error:

`ryp.r("library(arrow)")`

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/user/.conda/envs/global/lib/python3.12/site-packages/ryp.py", line 1314, in r
>     raise RuntimeError(error_message)
> RuntimeError: package or namespace load failed for ‘arrow’ in dyn.load(file, DLLpath = DLLpath, ...):
>  unable to load shared object '/home/user/R/x86_64-pc-linux-gnu-library/4.3/arrow/libs/arrow.so':
>   /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0
> >>>  

I'm using 

> Python 3.12.5 | packaged by Anaconda, Inc. | (main, Sep 12 2024, 18:27:27) [GCC 11.2.0] on linux

Have you seen this before? I don't understand why it only happens when I load it inside ryp.

> $ R
> 
> R version 4.3.3 (2024-02-29) -- "Angel Food Cake"
> Copyright (C) 2024 The R Foundation for Statistical Computing
> Platform: x86_64-pc-linux-gnu (64-bit)
> 
> R is free software and comes with ABSOLUTELY NO WARRANTY.
> You are welcome to redistribute it under certain conditions.
> Type 'license()' or 'licence()' for distribution details.
> 
>   Natural language support but running in an English locale
> 
> R is a collaborative project with many contributors
>  Type 'contributors()' for more information and
> 'citation()' on how to cite R or R packages in publications.
> 
> Type 'demo()' for some demos, 'help()' for on-line help, or
> 'help.start()' for an HTML browser interface to help.
> Type 'q()' to quit R.
> 
> [1] "Loading .Rprofile"
> > library(arrow)
> 
> Attaching package: ‘arrow’
> 
> The following object is masked from ‘package:utils’:
> 
>     timestamp
> 
> >

**Comment by Wainberg** [comment] 2024-11-07 20:15
Thanks for your help raising these issues! This works fine on my end on Linux, Windows and Mac, so it seems configuration-specific. 

It looks like the root cause is a [misconfiguration in conda](https://github.com/conda/conda/issues/12287#issuecomment-1443016695), which can be fixed by downgrading your `libffi` with `conda install libffi==3.3`.

**Comment by fkgruber** [comment] 2024-11-07 21:18
thanks I compare a working conda enviroment with this one and the solution was to do:
conda install libffi==3.4.2 cffi==1.17.1 -c conda-forge

**Closed** 2024-11-07 21:20 UTC
